/**
 * Default wordlist of common table names for vibe-coded Supabase apps.
 *
 * Used when the caller doesn't supply `--tables` explicitly. Supabase locks
 * the OpenAPI spec endpoint to the service_role key (as of mid-2026), so we
 * cannot enumerate tables with the anon key. This wordlist covers the
 * tables that AI codegen tools (Cursor, Lovable, Bolt) generate by default.
 *
 * Order: most-common first (slight latency win when we early-out on
 * concurrent batches).
 */
export const DEFAULT_TABLE_WORDLIST: string[] = [
  // User-account primitives — generated by virtually every AI scaffold
  "users",
  "profiles",
  "accounts",
  "customers",
  "members",
  "people",
  "auth_users",

  // Content / messaging
  "posts",
  "messages",
  "comments",
  "threads",
  "conversations",
  "chats",
  "replies",
  "articles",
  "blog_posts",
  "content",
  "notes",
  "drafts",
  "feedback",

  // Commerce / billing
  "orders",
  "products",
  "items",
  "cart",
  "carts",
  "purchases",
  "invoices",
  "subscriptions",
  "plans",
  "prices",
  "payments",
  "transactions",
  "receipts",
  "coupons",
  "discounts",

  // Engagement / social
  "likes",
  "reactions",
  "votes",
  "ratings",
  "reviews",
  "follows",
  "followers",
  "following",
  "friends",
  "friendships",
  "notifications",
  "events",
  "activities",

  // Files / media
  "files",
  "uploads",
  "media",
  "images",
  "documents",
  "attachments",
  "assets",

  // Workflow / productivity
  "todos",
  "tasks",
  "projects",
  "workspaces",
  "teams",
  "boards",
  "lists",
  "cards",
  "categories",
  "tags",
  "labels",

  // Auth / sessions
  "sessions",
  "tokens",
  "api_keys",
  "credentials",
  "permissions",
  "roles",
  "invitations",
  "invites",

  // Logs / metrics
  "logs",
  "analytics",
  "metrics",
  "stats",
  "events_log",
  "audit_logs",

  // Settings / config
  "settings",
  "preferences",
  "configurations",
  "config",

  // Habit / wellness (CardHabit-shaped apps)
  "habits",
  "streaks",
  "completions",
  "commitments",
  "card_draws",
  "vault_cards",
  "social_actions",
  "archetypes",

  // Generic
  "data",
  "entries",
  "records",
  "history",
  "favorites",
  "bookmarks",
];
